[tool.poetry]
name = "dm-codex-py"
version = "0.1.0"
description = "Dungeon Master's Codex API"
authors = ["Lando <landonlewisturner@gmail.com>"]
license = "GNU GENERAL PUBLIC LICENSE"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0.0"
flask-login = "^0.6.2"
flask-bcrypt = "^1.0.1"
flask-sqlalchemy = "^3.1.1"
flask-testing = "^0.8.1"
python-decouple = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
